/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CditBonjour */

#ifndef _Included_CditBonjour
#define _Included_CditBonjour
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CditBonjour
 * Method:    ditBonjour
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CditBonjour_ditBonjour
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
